<?php
namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UsersSeeder extends Seeder
{
    public function run()
    {        
        $data = [
            [                
                'company_id'        => 0,
                'email'             => 'admin@nfsolution.com.br',
                'password'          => password_hash('Fejao$8801', PASSWORD_DEFAULT),
                'role'              => 'master',
                'name'              => 'Felipe de Oliveira',
                'cpf'               => $this->cleanMask('415.734.858-37'),
                'rg'                => $this->cleanMask('42.914.497-0'),                
                'date_of_birth'     => '1994-10-03',                
                'gender'            => 'male',
                'zip_code'          => $this->cleanMask('03728-190'),
                'address_1'         => 'Rua Augusto Ambros',
                'address_2'         => 'Bloco A apt 82',
                'number'            => '173',
                'neighborhood'      => 'Jardim Castelo',
                'city'              => 'São Paulo',
                'state'             => 'SP',
                'phone_1'           => $this->cleanMask('(11) 96451-3763'),
                'phone_2'           => null
            ],
            [                
                'company_id'        => 1,
                'email'             => 'simonepatricialucianamartins@directnet.com.br',
                'password'          => password_hash('Q2KbpxcejX', PASSWORD_DEFAULT),
                'role'              => 'manager',
                'name'              => 'Simone Patrícia Luciana Martins',
                'cpf'               => $this->cleanMask('051.860.879-47'),
                'rg'                => $this->cleanMask('35.866.874-8'),                
                'date_of_birth'     => '1982-06-04',                
                'gender'            => 'female',
                'zip_code'          => $this->cleanMask('65047-760'),
                'address_1'         => 'Rua Petrônio Portela',
                'address_2'         => null,
                'number'            => '205',
                'neighborhood'      => 'Vera Cruz',
                'city'              => 'São Luís',
                'state'             => 'MA',
                'phone_1'           => $this->cleanMask('(98) 2873-8383'),
                'phone_2'           => $this->cleanMask('(98) 99423-7786')
            ],
            [                
                'company_id'        => 1,
                'email'             => 'eedsonkauedasilva@img.com.br',
                'password'          => password_hash('rnfAMIDflw', PASSWORD_DEFAULT),
                'role'              => 'common',
                'name'              => 'Edson Kauê da Silva',
                'cpf'               => $this->cleanMask('323.560.347-65'),
                'rg'                => $this->cleanMask('33.334.879-5'),                
                'date_of_birth'     => '1985-12-03',                
                'gender'            => 'male',
                'zip_code'          => $this->cleanMask('06604-235'),
                'address_1'         => 'Viela Terezinha Agostinho dos Santos',
                'address_2'         => null,
                'number'            => '104',
                'neighborhood'      => 'Jardim Brotinho',
                'city'              => 'Jandira',
                'state'             => 'SP',
                'phone_1'           => $this->cleanMask('(11) 3752-8660'),
                'phone_2'           => $this->cleanMask('(11) 98372-5722')
            ], 
            [                
                'company_id'        => 2,
                'email'             => 'lorenaantoniabarbaramoreira@eton.com.br',
                'password'          => password_hash('ZrK56m99UT', PASSWORD_DEFAULT),
                'role'              => 'manager',
                'name'              => 'Lorena Antônia Bárbara Moreira',
                'cpf'               => $this->cleanMask('415.240.073-07'),
                'rg'                => $this->cleanMask('40.367.821-3'),                
                'date_of_birth'     => '1975-09-20',                
                'gender'            => 'female',
                'zip_code'          => $this->cleanMask('69038-256'),
                'address_1'         => 'Rua Milagres',
                'address_2'         => null,
                'number'            => '619',
                'neighborhood'      => 'Lírio do Vale',
                'city'              => 'Manaus',
                'state'             => 'AM',
                'phone_1'           => $this->cleanMask('(92) 3905-5152'),
                'phone_2'           => $this->cleanMask('(92) 98558-9129')
            ],            
            [                
                'company_id'        => 2,
                'email'             => 'pedrohenrique@flir.com.br',
                'password'          => password_hash('StF5i5gxdT', PASSWORD_DEFAULT),
                'role'              => 'common',
                'name'              => 'Pedro Henrique Joaquim Nicolas da Mata',
                'cpf'               => $this->cleanMask('176.666.886-01'),
                'rg'                => $this->cleanMask('16.491.414-6'),                
                'date_of_birth'     => '1980-12-29',                
                'gender'            => 'male',
                'zip_code'          => $this->cleanMask('40220-830'),
                'address_1'         => 'Vila Dulce',
                'address_2'         => null,
                'number'            => '532',
                'neighborhood'      => 'Engenho Velho da Federação',
                'city'              => 'Salvador',
                'state'             => 'BA',
                'phone_1'           => $this->cleanMask('(71) 3724-6777'),
                'phone_2'           => $this->cleanMask('(71) 98249-6604')
            ], 
            [                
                'company_id'        => 3,
                'email'             => 'isabelagabriellyninapereira-95@plenamenterh.com.br',
                'password'          => password_hash('ANqQgLI1KT', PASSWORD_DEFAULT),
                'role'              => 'manager',
                'name'              => 'Isabela Gabrielly Nina Pereira',
                'cpf'               => $this->cleanMask('382.258.391-02'),
                'rg'                => $this->cleanMask('12.067.099-9'),                
                'date_of_birth'     => '1962-03-25',                
                'gender'            => 'female',
                'zip_code'          => $this->cleanMask('78734-065'),
                'address_1'         => 'Rua A',
                'address_2'         => null,
                'number'            => '993',
                'neighborhood'      => 'Residencial Paraíso',
                'city'              => 'Rondonópolis',
                'state'             => 'MT',
                'phone_1'           => $this->cleanMask('(66) 3749-3464'),
                'phone_2'           => $this->cleanMask('(66) 99295-1188')
            ],
            [                
                'company_id'        => 3,
                'email'             => 'sebastianajennifer@scalioni.com.br',
                'password'          => password_hash('gGnRklM5ZG', PASSWORD_DEFAULT),
                'role'              => 'common',
                'name'              => 'Sebastiana Jennifer Esther Monteiro',
                'cpf'               => $this->cleanMask('987.499.389-83'),
                'rg'                => $this->cleanMask('33.486.182-2'),                
                'date_of_birth'     => '1960-11-14',                
                'gender'            => 'female',
                'zip_code'          => $this->cleanMask('21340-220'),
                'address_1'         => 'Rua Marques de Aguiar',
                'address_2'         => null,
                'number'            => '715',
                'neighborhood'      => 'Oswaldo Cruz',
                'city'              => 'Rio de Janeiro',
                'state'             => 'RJ',
                'phone_1'           => $this->cleanMask('(21) 2986-8104'),
                'phone_2'           => $this->cleanMask('(21) 98240-1718')
            ],
            [                
                'company_id'        => 4,
                'email'             => 'luziaaparecidacastro@mcexecutiva.com.br',
                'password'          => password_hash('ofaJsUxpZN', PASSWORD_DEFAULT),
                'role'              => 'manager',
                'name'              => 'Luzia Aparecida Castro',
                'cpf'               => $this->cleanMask('884.296.904-41'),
                'rg'                => $this->cleanMask('29.188.072-1'),                
                'date_of_birth'     => '1976-08-05',                
                'gender'            => 'female',
                'zip_code'          => $this->cleanMask('69010-176'),
                'address_1'         => 'Beco Pablo Casais',
                'address_2'         => null,
                'number'            => '800',
                'neighborhood'      => 'Centro',
                'city'              => 'Manaus',
                'state'             => 'AM',
                'phone_1'           => $this->cleanMask('(92) 3970-0193'),
                'phone_2'           => $this->cleanMask('(92) 99503-9265')
            ],   
            [                
                'company_id'        => 4,
                'email'             => 'marciajenniferfernandes_@patrilarm.com.br',
                'password'          => password_hash('3brd2ECkIJ', PASSWORD_DEFAULT),
                'role'              => 'common',
                'name'              => 'Márcia Jennifer Fernandes',
                'cpf'               => $this->cleanMask('405.435.701-69'),
                'rg'                => $this->cleanMask('25.578.526-4'),                
                'date_of_birth'     => '1998-09-27',                
                'gender'            => 'female',
                'zip_code'          => $this->cleanMask('59064-350'),
                'address_1'         => 'Rua Floresta',
                'address_2'         => null,
                'number'            => '372',
                'neighborhood'      => 'Lagoa Nova',
                'city'              => 'Natal',
                'state'             => 'RN',
                'phone_1'           => $this->cleanMask('(84) 3692-5188'),
                'phone_2'           => $this->cleanMask('(84) 98380-3806')
            ],   
            [                
                'company_id'        => 5,
                'email'             => 'alinemariataniamoreira-78@galvao.com',
                'password'          => password_hash('SGSZYnXqmO', PASSWORD_DEFAULT),
                'role'              => 'manager',
                'name'              => 'Aline Maria Tânia Moreira',
                'cpf'               => $this->cleanMask('290.239.398-91'),
                'rg'                => $this->cleanMask('40.678.342-1'),                
                'date_of_birth'     => '2003-04-12',                
                'gender'            => 'female',
                'zip_code'          => $this->cleanMask('78550-480'),
                'address_1'         => 'Rua das Guazumas',
                'address_2'         => null,
                'number'            => '781',
                'neighborhood'      => 'Parque das Araras',
                'city'              => 'Sinop',
                'state'             => 'MT',
                'phone_1'           => $this->cleanMask('(66) 2695-1627'),
                'phone_2'           => $this->cleanMask('(66) 99766-5083')
            ],   
            [                
                'company_id'        => 5,
                'email'             => 'brunoluizbernardogoncalves-75@sorocaba.com',
                'password'          => password_hash('YHfLDlBzAK', PASSWORD_DEFAULT),
                'role'              => 'common',
                'name'              => 'Bruno Luiz Bernardo Gonçalves',
                'cpf'               => $this->cleanMask('247.908.741-76'),
                'rg'                => $this->cleanMask('46.717.559-7'),                
                'date_of_birth'     => '1978-09-20',                
                'gender'            => 'male',
                'zip_code'          => $this->cleanMask('53415-308'),
                'address_1'         => '8ª Travessa General Canabarros',
                'address_2'         => null,
                'number'            => '424',
                'neighborhood'      => 'Artur Lundgren I',
                'city'              => 'Paulista',
                'state'             => 'PE',
                'phone_1'           => $this->cleanMask('(81) 3991-4274'),
                'phone_2'           => $this->cleanMask('(81) 98772-2180')
            ],          
        ];

        $this->db->table('users')->insertBatch($data);
    }

    private function cleanMask($value)
    {        
        return trim(preg_replace('/[^0-9]+/', '', $value));
    }
}